/* eslint-disable @next/next/no-css-tags */
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import { Suspense } from "react";
import Loading from "./components/loading";
// import Script from "next/script";
  
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <title>INC. - Minimal Creative Agency Website HTML Template</title>
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        {/* <!-- Place favicon.ico in the root directory --> */}
        <link rel="shortcut icon" type="image/x-icon" href="png/favicon.png" />
        <link rel="stylesheet" href="/styles/bootstrap.css" />
        <link rel="stylesheet" href="/styles/meanmenu.css" />
        <link rel="stylesheet" href="/styles/animate.css" />
        <link rel="stylesheet" href="/styles/swiper-bundle.css" />
        <link rel="stylesheet" href="/styles/backtotop.css" />
        <link rel="stylesheet" href="/styles/magnific-popup.css" />
        <link rel="stylesheet" href="/styles/nice-select.css" />
        <link rel="stylesheet" href="/styles/font-awesome-pro.css" />
        <link rel="stylesheet" href="/styles/spacing.css" />
        <link rel="stylesheet" href="/styles/main.css" />
      </head>
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          {children}
        </Suspense>

      <Script src="/scripts/jquery.js"></Script>
      <Script src="/scripts/waypoints.js"></Script>
      <Script src="/scripts/bootstrap-bundle.js"></Script>
      <Script src="/scripts/meanmenu.js"></Script>
      <Script src="/scripts/swiper-bundle.js"></Script>
      <Script src="/scripts/magnific-popup.js"></Script>
      <Script src="/scripts/backtotop.js"></Script>
      <Script src="/scripts/nice-select.js"></Script>
      <Script src="/scripts/counterup.js"></Script>
      <Script src="/scripts/wow.js"></Script>
      <Script src="/scripts/isotope-pkgd.js"></Script>
      <Script src="/scripts/imagesloaded-pkgd.js"></Script>
      <Script src="/scripts/ajax-form.js"></Script>
      <Script src="/scripts/main.js"></Script>
      </body>
    </html>
  );
}
